# Jekyll configuration for NovaEval documentation
title: NovaEval Documentation
description: A comprehensive, open-source LLM evaluation framework for testing and benchmarking AI models
url: https://noveum.github.io/NovaEval
baseurl: /NovaEval

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
lang: en
author:
  name: Noveum AI
  email: team@noveum.ai
  url: https://noveum.ai

# Social links
github_username: Noveum
twitter_username: noveumAI

# Navigation configuration for minima theme
header_pages:
  - index.md
  - getting-started.md
  - user-guide.md
  - api-reference.md
  - cli-reference.md
  - examples.md
  - contributing.md
  - LOCAL_DEVELOPMENT.md

# Minima theme settings
minima:
  social_links:
    github: Noveum
    twitter: noveumAI
  show_excerpts: true

# Footer links
footer_links:
  - title: Noveum.ai
    url: https://noveum.ai
  - title: Documentation
    url: https://noveum.ai/en/docs
  - title: GitHub
    url: https://github.com/Noveum/NovaEval
  - title: Issues
    url: https://github.com/Noveum/NovaEval/issues

# SEO
google_analytics: # Add your GA tracking ID
logo: /assets/images/logo.png

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
