# Jekyll configuration for NovaEval documentation
title: NovaEval Documentation
description: >-
  NovaEval is a comprehensive, open-source AI model evaluation framework that simplifies
  the complex process of testing and benchmarking language models. Whether you're a
  researcher comparing model performance, a developer ensuring quality in production,
  or a data scientist benchmarking custom models, NovaEval provides the tools you need.
tagline: Comprehensive AI Model Evaluation Framework
url: https://novaeval.com
baseurl: ""

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
lang: en
timezone: America/New_York

# Author and company information
author:
  name: Noveum AI
  email: team@noveum.ai
  url: https://noveum.ai
  twitter: noveumAI
  github: Noveum

# Social links
github_username: Noveum
twitter_username: noveumAI

# Keywords for SEO
keywords: >-
  AI evaluation, LLM testing, machine learning benchmarks, model evaluation framework,
  OpenAI, Anthropic, Claude, GPT, AI models, language model testing, AI benchmarking,
  ML evaluation, artificial intelligence, model comparison, AI performance testing

# Navigation configuration for minima theme
header_pages:
  - index.md
  - getting-started.md
  - user-guide.md
  - api-reference.md
  - cli-reference.md
  - examples.md
  - contributing.md
  - LOCAL_DEVELOPMENT.md

# Minima theme settings
minima:
  social_links:
    github: Noveum
    twitter: noveumAI
  show_excerpts: true

# Footer links
footer_links:
  - title: Noveum.ai
    url: https://noveum.ai
  - title: Documentation
    url: https://noveum.ai/en/docs
  - title: GitHub
    url: https://github.com/Noveum/NovaEval
  - title: Issues
    url: https://github.com/Noveum/NovaEval/issues

# SEO and Social Media
google_analytics: G-MYX27CJJYK
logo: https://blog.api.market/wp-content/uploads/2025/07/NovaEval_banner_SEO.png
canonical_url: https://novaeval.com/

# Twitter Card settings
twitter:
  username: noveumAI
  card: summary_large_image

# Open Graph settings
og_image: https://blog.api.market/wp-content/uploads/2025/07/NovaEval_banner_SEO.png
og_image_alt: "NovaEval - Comprehensive AI Model Evaluation Framework"

# Additional SEO settings
webmaster_verifications:
  google: # Add Google Search Console verification code
  bing: # Add Bing Webmaster verification code

# Social media profiles
social:
  name: Noveum AI
  links:
    - https://x.com/noveumAI
    - https://github.com/Noveum
    - https://noveum.ai
    - https://linkedin.com/company/noveum-ai

# Site verification and additional meta
verification:
  google: # Add Google verification meta tag content
  bing: # Add Bing verification meta tag content

# Additional SEO meta tags that jekyll-seo-tag will use
seo:
  type: Organization
  name: NovaEval
  links:
    - https://novaeval.com
    - https://github.com/Noveum/NovaEval
    - https://twitter.com/noveumAI

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: https://blog.api.market/wp-content/uploads/2025/07/NovaEval_banner_SEO.png
      author: Noveum AI
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: https://blog.api.market/wp-content/uploads/2025/07/NovaEval_banner_SEO.png
      author: Noveum AI
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
      image: https://blog.api.market/wp-content/uploads/2025/07/NovaEval_banner_SEO.png
      author: Noveum AI
